typography_spectrum: 0.6339384708553553
color:
  brandStrength: 0.8104953332804143
  lightness: 0.13287394167855382
  saturation: 0.9328197229187936
  rhythmicContrast: 0.7009568093344569
  brandColors:
    - '#334D5C'
    - '#45B29D'
    - '#EFC94C'
    - '#E27A3F'
    - '#DF5A49'
layout_spectrum: 0.6935878898948431
name: Al borde del Camino
navigation:
  - name: Mandala Digital
    url: 'http://www.mandaladigital.pe'
    type: external
  - name: Al borde del camino esâ€¦
    id: 70f50f7a-963f-42d9-8cea-fd513d2524de
    type: content
title: Al borde del Camino
description: descanso digital productivo
